name: Evotech Bot

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Evotech Bot
        uses: yossi-asher/evotech-bot@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
